include $(GOROOT)/src/Make.inc

TARG=medstime
GOFILES=\
	../shared/db.go\
	../shared/account.go\
	../shared/schedule.go\
	../shared/messageinterface.go\
	session.go\
	sessionmanager.go\
	index.go\
	main.go

include $(GOROOT)/src/Make.cmd
