include $(GOROOT)/src/Make.inc

TARG=medstime
GOFILES=\
	../shared/account.go\
	../shared/accountmanager.go\
	../shared/schedule.go\
	../shared/schedulemanager.go\
	../shared/messageinterface.go\
	session.go\
	sessionmanager.go\
	../shared/errors.go\
	site_account.go\
	site_login.go\
	site_signup.go\
	site_index.go\
	main.go

include $(GOROOT)/src/Make.cmd
