include $(GOROOT)/src/Make.inc

TARG=smsd
GOFILES=\
	../shared/db.go\
	../shared/account.go\
	../shared/accountmanager.go\
	../shared/schedule.go\
	../shared/schedulemanager.go\
	../shared/errors.go\
	../shared/messageinterface.go\
	job.go\
	main.go

include $(GOROOT)/src/Make.cmd
